import { createGlobalStyle } from 'styled-components';
export const GlobalStyle = createGlobalStyle`
  *{box-sizing:border-box} html,body,#root{height:100%;min-width:0} html,body{overflow-x:hidden}
  html{color-scheme:dark} body{margin:0;font-family:Inter,Manrope,system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif;line-height:1.55;
    color:${({theme})=>theme.colors.text};
    background:
      radial-gradient(900px 680px at 12% 0%, rgba(212,175,55,.13), transparent 66%),
      radial-gradient(900px 640px at 92% 84%, rgba(156,122,24,.09), transparent 68%),
      linear-gradient(145deg, #070809, #0D0F12 48%, #070809);
    background-attachment:fixed;
  }
  body::before{content:'';position:fixed;inset:0;z-index:-1;pointer-events:none;opacity:.14;background-image:linear-gradient(117deg,transparent 0 46%,rgba(255,255,255,.028) 47%,transparent 49%),repeating-radial-gradient(ellipse at 30% 20%,rgba(255,255,255,.03) 0 1px,transparent 1px 9px);mix-blend-mode:screen}
  ::selection{background:${({theme})=>theme.colors.accentSoft}}
  a{color:${({theme})=>theme.colors.accentStrong};text-decoration:none} a:hover{text-decoration:none;color:#fff2c7}
  h1{font-size:clamp(1.8rem,5vw,2.8rem);margin:0 0 10px} h1,h2,h3,h4{font-family:Inter,Manrope,system-ui,sans-serif;font-weight:700;letter-spacing:-.02em;background:linear-gradient(115deg,${({theme})=>theme.colors.accentStrong},${({theme})=>theme.colors.accent},${({theme})=>theme.colors.text});background-clip:text;-webkit-background-clip:text;color:transparent} h2,h3{overflow-wrap:anywhere}
  button,a,input,select,textarea{touch-action:manipulation} button:focus-visible,a:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible,summary:focus-visible{outline:2px solid ${({theme})=>theme.colors.accent};outline-offset:3px}
  input,select,textarea{width:100%;min-height:46px;padding:11px 13px;border-radius:${({theme})=>theme.radii.md};border:1px solid ${({theme})=>theme.colors.border};background:rgba(12,14,18,.72);color:${({theme})=>theme.colors.text};font:inherit;transition:border-color .18s,box-shadow .18s,background .18s}input::placeholder,textarea::placeholder{color:rgba(246,231,184,.34)}input:focus,select:focus,textarea:focus{border-color:rgba(212,175,55,.48);box-shadow:0 0 0 4px rgba(212,175,55,.12);background:rgba(12,14,18,.86);outline:0}
  textarea{resize:vertical;min-height:82px} option{background:#0D0F12;color:${({theme})=>theme.colors.text}}
  label{display:grid;gap:6px;font-size:13px;color:${({theme})=>theme.colors.textSecondary}}
  .responsive-form,.toolbar{display:flex;gap:9px;flex-wrap:wrap;align-items:end}.responsive-form>*{flex:1 1 150px}.toolbar>input{flex:1 1 260px}.toolbar>select{flex:0 1 190px}.toolbar button{width:auto}
  .checkbox{display:flex;grid-auto-flow:column;align-items:center;gap:7px;white-space:nowrap}.checkbox input{width:auto;min-height:auto}
  .data-table{width:100%;border-collapse:collapse}.data-table th,.data-table td{text-align:left;padding:12px 10px;vertical-align:top;border-top:1px solid rgba(255,255,255,.1)}.data-table th{font-size:12px;text-transform:uppercase;letter-spacing:.04em;opacity:.68}
  .status-pill{display:inline-block;padding:5px 9px;border:1px solid ${({theme})=>theme.colors.border};border-radius:999px;background:${({theme})=>theme.colors.accentSoft};color:${({theme})=>theme.colors.accentStrong};font-size:11px;font-weight:800;letter-spacing:.04em;text-transform:uppercase}
  .detail-grid{display:grid;gap:16px;grid-template-columns:repeat(2,minmax(0,1fr))}.detail-grid> :last-child:nth-child(odd){grid-column:1/-1}
  .field-grid{display:grid;gap:12px;grid-template-columns:repeat(2,minmax(0,1fr))}.span-2{grid-column:1/-1}
  .timeline{display:grid;gap:0}.timeline>div{border-left:2px solid rgba(212,175,55,.38);padding:0 0 18px 14px}.timeline small{display:block;color:${({theme})=>theme.colors.subtle};margin-top:3px}.timeline p{margin:7px 0 0;white-space:pre-wrap}
  .call-brief{margin-top:18px;padding:16px;border:1px solid rgba(212,175,55,.16);border-radius:${({theme})=>theme.radii.md};background:rgba(7,8,10,.54);box-shadow:inset 0 1px rgba(255,255,255,.035)}.call-brief h4{margin:0 0 12px}.call-brief dl{display:grid;grid-template-columns:minmax(120px,.35fr) 1fr;gap:8px 16px;margin:0}.call-brief dt{font-size:12px;text-transform:uppercase;letter-spacing:.04em;color:${({theme})=>theme.colors.subtle}}.call-brief dd{margin:0;white-space:pre-wrap}
  .metric-row{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px}.metric-row span{display:grid;gap:5px;padding:14px;border:1px solid ${({theme})=>theme.colors.border};border-radius:${({theme})=>theme.radii.sm};background:rgba(255,255,255,.025)}.metric-row strong{font-size:23px;color:${({theme})=>theme.colors.accentStrong}}
  .page-stack{display:grid;grid-template-columns:minmax(0,1fr);gap:16px;min-width:0;animation:page-in .42s ease both}.page-stack>*{min-width:0}.muted{color:${({theme})=>theme.colors.subtle};opacity:1}.error-text{color:${({theme})=>theme.colors.danger}}.success-text{color:${({theme})=>theme.colors.success}}.mobile-only{display:none}.table-scroll{overflow-x:auto;max-width:100%}@keyframes page-in{from{opacity:0;transform:translateY(7px)}to{opacity:1;transform:none}}
  details>summary{min-height:44px;display:flex;align-items:center;cursor:pointer;list-style:none}details>summary::-webkit-details-marker{display:none}details>summary::after{content:'+';margin-left:auto;font-size:20px;opacity:.65}details[open]>summary::after{content:'−'}.section-body{padding-top:14px}.progressive-form{display:grid;gap:10px}.progressive-form>details{border-top:1px solid rgba(255,255,255,.1)}
  .form-actions,.card-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:14px}.form-actions>*{flex:1 1 180px}.secondary-button{margin-top:12px;background:rgba(255,255,255,.1)}
  .mapping-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:10px}.import-preview{display:grid;gap:8px;max-height:260px;overflow:auto;margin:10px 0}.import-preview pre{min-width:0;overflow:auto;margin:0;padding:10px;border-radius:8px;background:rgba(0,0,0,.3);font-size:11px}
  .lead-list-card{max-width:100%;overflow-x:auto;overscroll-behavior-inline:contain}.lead-card{display:grid;gap:10px;padding:16px;border:1px solid ${({theme})=>theme.colors.border};border-radius:${({theme})=>theme.radii.md};background:rgba(8,10,12,.58);box-shadow:inset 0 1px rgba(255,255,255,.035)}.lead-card p,.lead-card h3{margin:0}.lead-card-head{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.phone-link{font-size:17px;font-weight:700}.line-clamp{display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.action-link{min-height:44px;display:grid;place-items:center;flex:1;padding:9px 12px;border:1px solid ${({theme})=>theme.colors.border};border-radius:${({theme})=>theme.radii.md};background:rgba(255,255,255,.03);text-align:center}.action-link.primary{background:linear-gradient(135deg,rgba(212,175,55,.22),rgba(156,122,24,.16));border-color:${({theme})=>theme.colors.borderGold};color:${({theme})=>theme.colors.text};font-weight:800;box-shadow:${({theme})=>theme.shadows.glow}}.card-action-button{font:inherit;cursor:pointer}.card-action-button:disabled{opacity:.55;cursor:not-allowed}
  .detail-header{display:flex;align-items:end;justify-content:space-between;gap:14px}.detail-header h1{margin:8px 0 0}.technical-id{font-size:12px;opacity:.55}.technical-id code{display:block;overflow-wrap:anywhere;padding-top:5px}.detail-section{scroll-margin-top:76px}.section-heading{margin-bottom:12px}.sticky-actions{display:flex;justify-content:flex-end}.feedback-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin:0}.feedback-grid>div{padding:12px;border-radius:10px;background:rgba(255,255,255,.04)}.feedback-grid dt{font-size:12px;opacity:.62}.feedback-grid dd{margin:5px 0 0;white-space:pre-wrap}.call-task-list{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:12px}
  .transcript-heading{display:flex;justify-content:flex-end;margin-bottom:12px}.transcript-status.partial{color:${({theme})=>theme.colors.accentStrong}}.transcript-status.final{color:${({theme})=>theme.colors.success}}.transcript-turns{display:grid;gap:12px}.transcript-turn{min-width:0;max-width:88%;padding:14px 16px;border:1px solid ${({theme})=>theme.colors.border};border-radius:${({theme})=>theme.radii.md};background:rgba(12,14,18,.56);box-shadow:0 8px 22px rgba(0,0,0,.18)}.transcript-turn.emma{margin-left:auto;border-color:rgba(212,175,55,.24);background:linear-gradient(135deg,rgba(212,175,55,.11),rgba(7,8,10,.66))}.transcript-meta{display:flex;align-items:baseline;gap:9px;color:${({theme})=>theme.colors.accent};font-size:12px;text-transform:uppercase;letter-spacing:.07em}.transcript-meta time{min-width:42px;font-variant-numeric:tabular-nums;color:${({theme})=>theme.colors.subtle}}.transcript-turn p{margin:7px 0 0;overflow-wrap:anywhere;white-space:pre-wrap;line-height:1.58}.transcript-notice{margin:16px 0 0;font-size:12px;color:${({theme})=>theme.colors.subtle}}
  .map-result{display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:12px;border:1px solid rgba(255,255,255,.12);border-radius:12px;padding:10px 12px}.map-result>input{width:22px;min-height:22px}
  .nav-label{display:block;max-width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
  @media(max-width:900px){
    .detail-grid,.field-grid,.feedback-grid{grid-template-columns:1fr}.detail-grid>*,.span-2{grid-column:auto}.call-brief dl{grid-template-columns:1fr}.call-brief dd{margin-bottom:5px}
    .desktop-only{display:none!important}.mobile-only{display:grid}.mobile-lead-list{gap:12px}.lead-list-card{padding:12px}.toolbar{display:grid;grid-template-columns:1fr;width:100%}.toolbar>*{width:100%!important}.checkbox{min-height:44px;white-space:normal}
    .responsive-form{display:grid;grid-template-columns:1fr}.form-actions{display:grid;grid-template-columns:1fr}.detail-header{align-items:stretch;display:grid}.detail-header>button{position:sticky;top:64px;z-index:8}.sticky-actions{position:sticky;z-index:10;bottom:calc(69px + env(safe-area-inset-bottom));display:grid;grid-template-columns:1fr;gap:8px;padding:8px;margin:0 -4px;background:rgba(8,10,14,.92);backdrop-filter:blur(10px)}.sticky-actions button{width:100%}.mapping-grid{grid-template-columns:1fr}
    .data-table th,.data-table td{padding:10px 7px}.call-task-list{grid-template-columns:1fr}
    .map-result{grid-template-columns:auto minmax(0,1fr)}.map-result>button{grid-column:1/-1}
  }
  @media(max-width:560px){.transcript-turn{max-width:100%}}
  @media(prefers-reduced-motion:reduce){*,*::before,*::after{animation:none!important;transition:none!important;scroll-behavior:auto!important}}
`;
